on:
  schedule:
    - cron: '0 10,13,18 * * *'
  workflow_dispatch:

name: Update report

jobs:
  webscraping:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Extract R version from lockfile
        run: printf 'R_VERSION=%s\n' "$(jq --raw-output .R.Version renv.lock)" >> $GITHUB_ENV

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
          
      - name: Setup system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libsodium-dev \
            libmkl-rt \
            libglpk-dev \
            libxml2-dev

      - name: Restore non-renv packages from cache
        uses: actions/cache@v3
        env:
          CACHE_KEY_NON_RENV: packages-${{ runner.arch }}-${{ runner.os }}-${{ env.R_VERSION }}-${{ hashFiles('renv.lock') }}
        with:
          path: |
            renv/library/*
            !renv/library/renv
          key: ${{ env.CACHE_KEY_NON_RENV }}
          restore-keys: |
            packages-${{ runner.arch }}-${{ runner.os }}-${{ env.R_VERSION }}-
            packages-${{ runner.arch }}-${{ runner.os }}-

      - name: Sync renv with lockfile
        shell: Rscript {0}
        run: |
          options(renv.config.cache.symlinks = FALSE)
          renv::restore(clean = TRUE)

      - name: Render report
        run: |
          Rscript -e 'quarto::quarto_render(input = "docs/index.qmd")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs
          git commit -m "Automatic report update with GitHub actions" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

          
